# <font color='#B31B1B'> Getting Started </font>

In this course we will make use of python notebooks. There are many ways to create python code, including Jupyter Notebook, Visual Studio, Anaconda, etc. One quick way is to use Google Colab which already came with your Google account. You are welcome to set up your own python environment on your device (e.g. using Anaconda), we may not be able to help you with some issues you may encounter. 

Go to https://colab.research.google.com/ and sign in with a Google account. Then you can create a new notebook, open an existing notebook, or upload a notebook by clicking the "File" button in the top left of the window and choosing the respective option from the dropdown menu. For recitations, you may want to download the notebook from Canvas and then upload and open it in Google Colab so you can have your questions and answers next to each other. For homeworks you will likely create a new notebook from scratch.

Right under the "File" button are the "Code+" and "Text+" buttons. These let you add code cells and text cells respectively. Code cells are where you type your Python code and can run it by either clicking the play button that pops up on the left of the cell when you move your mouse over it or by clicking the cell and using the keyboard shortcut "Shift+Enter". The text cells let you add text/math in the notebook and is what allows us to display the text you're currently reading.

To save a notebook as a pdf to turn in (for homeworks or projects, no need to turn in for recitations), select "File" -> "Print" and then choose "Save as PDF" as the destination.

For other ways, for example, Jupyter, you may directly go to its website to download and start your notebook.

### <font color='#B31B1B'> Python Basics </font>

In [1]:
print("Hello Wolrd!")
#type("Hello Wolrd")

Hello Wolrd


In [6]:
#data types
data = [1,1.2,"Hello World!"] #list data type
n = len(data) #"len" function returns the number of elements

#for loop (you may try using whlie loop)
for i in range(n):
#for d in data:
    print(data[i], "type is ", type(data[i]))
    #print(d, "type is ", type(d))

1 type is  <class 'int'>
1.2 type is  <class 'float'>
Hello World! type is  <class 'str'>


In [7]:
type(data)

list

In [19]:
#list data type basics
L = [1,2,3] #easiest way of creating a list
L = [i for i in range(10)] #using for loop to create a list
#L = [i**2 for i in range(5)]
#print(L)

A = [1,2,3]
B = [4,5,6]
#"adding" two lists is equivalent to concatenating two lists
#print(A + B)

#you may also create a list of list
C = [[1,2,3],[4,5,6]]

In [25]:
#Function: It may received multiple inputs, or return nothing but
#a function must do something, e.g. "len" is a function
def sampleFN1(x):
    return x**2

def sampleFN2(x,y):
    return x**2 - y**2

def sampleFN3(text):
    return text[::-1] #reverting the given text

#"map" function: Applying the given function to given multiple input
result = map(len,C)
print(list(result))

[3, 3]


### <font color='#B31B1B'> Numpy Basics </font>

You may be used to writing for loops in other classes but in python, iterating over lists (e.g. `[1,2,3]`) and operating on each element is very slow. One reason is that the objects in these lists can be of different types and sizes, for example `a = [1,'hello', (3,4,5), myObject]` is valid Python. 

When working with numerical data, it's a good idea instead to use Numpy arrays where looping is done in optimized C code making use of vectorized operations. Consider two ways of applying a simple function to an array of numbers.

In [26]:
import numpy as np

In [27]:
# Using for loops and lists
y = []
for i in range(10):
    y.append(i**2)
print(y)

# Using list comprehensions
y = [i**2 for i in range(10)]
print(y)

# Using numpy arrays
x = np.arange(10)
y = x**2
print(y)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[ 0  1  4  9 16 25 36 49 64 81]


In [33]:
# Use %timeit cell magic to time execution
%timeit [i**2 for i in range(100)]
%timeit np.arange(100)**2

20 µs ± 293 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
1.07 µs ± 5.64 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [34]:
# Indexing and slicing
y = np.arange(10)**2
print(y[3:8])
mask = y > 5
print(mask)

# Indexing by boolean masks
print(y[mask])

[ 9 16 25 36 49]
[False False False  True  True  True  True  True  True  True]
[ 9 16 25 36 49 64 81]


In [39]:
# generate sample sequences using numpy
u = np.array([1,2,3])
v = np.array([4,5,6])
print("u = {}".format(u))
print("v = {}".format(v))
print("u + v = {}".format(u + v))
print("<u,v> = {}".format(u@v))
print("<u,v> = {}".format(u.dot(v)))

u = [1 2 3]
v = [4 5 6]
u + v = [5 7 9]
<u,v> = 32
<u,v> = 32


In [42]:
#matrices
J = np.array([[0,1],[-1,0]])
print(J@J)
print(J*J)
print(J.T)
print(J.shape)
print(J@np.ones(2))

#identity matrix
I = np.eye(3)
print(I)

[[-1  0]
 [ 0 -1]]
[[0 1]
 [1 0]]
[[ 0 -1]
 [ 1  0]]
(2, 2)
[ 1. -1.]


In [82]:
#linear algebra library (np.linalg)
u = np.array([3,4,5])
A = np.array([[1,4,7],
              [4,5,9],
              [7,8,9]])

u_norm = np.linalg.norm(u) #vector norms
eig_vals, eig_vecs = np.linalg.eig(A) #eigenvalues and vectors
A_inv = np.linalg.inv(A) #inverse function (don't recommend)